name: "Check Directory Changes"
description: "Check if a directory has changes"
inputs:
  dir:
    description: "Directory to check for changes"
    required: true
    
outputs:
  changed:
    value: ${{ steps.check.outputs.changed }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Make script executable
      run: chmod +x .github/scripts/is_changed.sh
      shell: bash

    - name: Check for changes
      id: check
      run: |
        if .github/scripts/is_changed.sh ${{ inputs.dir }}; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
