name: "Login, Build and Push Docker Image"
description: "Build and push to docker hub"
inputs:
  service:
    description: "Name of the service (e.g., frontend, backend1)"
    required: true
  tag:
    description: "Docker image tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push ${{ inputs.service }} Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.service }}
        file: ./${{ inputs.service }}/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }}
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service }}:latest 
