name: "Login, Build and Push Docker Image"
description: "Build and push to docker hub"
inputs:
  service:
    description: "Name of the service (e.g., frontend, backend1)"
    required: true
  tag:
    description: "Docker image tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.service }}-${{ inputs.tag }}-${{ hashFiles('${{ inputs.service }}/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.service }}-


    - name: Build and push ${{ inputs.service }} Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.service }}
        file: ./${{ inputs.service }}/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.service }}:latest 
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
