name: "Login, Build and Push Docker Image"
description: "Build and push to docker hub"
inputs:
  service:
    description: "Name of the service (e.g., frontend, backend1)"
    required: true
  tag:
    description: "Docker image tag"
    required: true
  package_artifact:
    description: "Whether to package the image as a TAR file"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2        
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.service }}-${{ inputs.tag }}-${{ hashFiles(format('{0}/Dockerfile', inputs.service)) }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ inputs.service }}-


    - name: Build and push ${{ inputs.service }} Image
      uses: docker/build-push-action@v5
      with:
        context: ./${{ inputs.service }}
        file: ./${{ inputs.service }}/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.service }}:latest 
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
    
    - name: Save image as TAR
      if: ${{ inputs.package_artifact == 'true' }}
      run: |
        docker pull ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }}
        echo "Saving to ${inputs.service}-${inputs.tag}.tar..."
        docker save ${{ env.DOCKERHUB_USERNAME }}/${{ inputs.service }}:${{ inputs.tag }} \
          > ${{ inputs.service }}-${{ inputs.tag }}.tar
      shell: bash
      
    - name: Upload image tar artifact
      if: ${{ inputs.package_artifact == 'true' }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.service }}-${{ inputs.tag }}
        path: ${{ inputs.service }}-${{ inputs.tag }}.tar
