name: Deploy 
run-name: ${{ github.actor }} is deploying.

on:
  workflow_dispatch:

env:
  PAGES_REPO: madhuSudanSharma1/blog-page
  PAGES_TOKEN: ${{ secrets.PAGES_TOKEN }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.0.0'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install --prefer-offline
        shell: bash

      - name: Build frontend
        run: |
          cd frontend
          yarn build
        env:
          VITE_CLERK_PUBLISHABLE_KEY: pk_test_ZnJlZS1xdWFnZ2EtMjIuY2xlcmsuYWNjb3VudHMuZGV2JA
          VITE_BACKEND1_BASE_URL: http://localhost:3000/
          VITE_BACKEND2_BASE_URL: http://localhost:3001/  
        shell: bash

      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PAGES_REPO }}
          token: ${{ env.PAGES_TOKEN }}
          path: pages-repo
          ref: main

      - name: Copy dist to GitHub Pages repo root
        run: |
          cp -r frontend/dist/. pages-repo/
        shell: bash

      - name: Commit and push to GitHub Pages repo
        run: |
          cd pages-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy frontend build  to root"
          git push origin main
        shell: bash