name: GitHub Actions For CI
run-name: ${{ github.actor }} is running a GitHub Actions workflow for CI

on: 
  pull_request:
    branches: [ "dev"]

  push:
    branches: [ "dev" ]

jobs:
# Runs on every thing PR or push to any branch
  commitlint:
    if: github.event_name == 'pull_request' 
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Commitlint
        run: |
          npm install --save-dev @commitlint/cli @commitlint/config-conventional
      - name: Add commitlint config
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
      - name: Run Commitlint
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=format:"%s" | npx commitlint


# Runs on every thing PR or push to any branch
  lint-all-services:
    name: Lint All Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run frontend lint & security
        uses: ./.github/actions/lint-and-security-checks
        with:
          directory: frontend
          
      - name: Run backend1 lint & security
        uses: ./.github/actions/lint-and-security-checks
        with:
          directory: backend1

      - name: Run backend2 lint & security
        uses: ./.github/actions/lint-and-security-checks
        with:
          directory: backend2

      - name: Final Status
        run: echo "All services passed lint and security checks."

# For All Pull Requests
  notify-slack-pr:
    name: Notify Slack on PR
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [commitlint, lint-all-services]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4   
  
      - name: Notify Slack
        uses: ./.github/actions/slack
        with:
          message: '{"text": "A new Pull Request was created by *${{ github.actor }}* targeting ${{ github.base_ref }} branch.\n<${{ github.event.pull_request.html_url }}|View PR>"}'

# For All Push
  notify-slack-push:
    name: Notify Slack on Push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ lint-all-services]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Slack
        uses: ./.github/actions/slack
        with:
          message: '{"text": "A new Push was made by *${{ github.actor }}* to ${{ github.base_ref }} branch."}'

## Push to Dev OR MAIN → Docker Build & Push
  version-services:
    name: Compute dev‑versions
    runs-on: ubuntu-latest
    needs: lint-all-services
    outputs:
      frontend: ${{ steps.f.outputs.version }}
      backend1:  ${{ steps.b1.outputs.version }}
      backend2:  ${{ steps.b2.outputs.version }}
      any-changed: ${{ steps.check.outputs.changed_any }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Version frontend
        id: f
        uses: paulhatch/semantic-version@latest
        with:
          change_path: frontend
          namespace: frontend
          tag_prefix: dev-

      - name: Version backend1
        id: b1
        uses: paulhatch/semantic-version@latest
        with:
          change_path: backend1
          namespace: backend1
          tag_prefix: dev-

      - name: Version backend2
        id: b2
        uses: paulhatch/semantic-version@latest
        with:
          change_path: backend2
          namespace: backend2
          tag_prefix: dev-

      - name: Check if any changed
        id: check
        run: |
          if [[ "${{ steps.f.outputs.changed }}" == "true" ]] || \
             [[ "${{ steps.b1.outputs.changed }}" == "true" ]] || \
             [[ "${{ steps.b2.outputs.changed }}" == "true" ]]; then
            echo "changed_any=true" >> $GITHUB_OUTPUT
          else
            echo "changed_any=false" >> $GITHUB_OUTPUT
          fi

  build-and-push-frontend:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [ lint-all-services]
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Check if frontend has changed
        id: check_frontend
        uses: ./.github/actions/has-changed
        with:
          dir: frontend

      - name: Set Docker image tag
        if: steps.check_frontend.outputs.changed == 'true'
        id: set
        run: |
          if [[ "${GITHUB_REF}" =~ ^refs/tags/ ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
            echo "tag=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build and Push Docker Image
        if: steps.check_frontend.outputs.changed == 'true'
        uses: ./.github/actions/build-and-push
        with:
          service: frontend
          tag: ${{ steps.set.outputs.tag }}
          package_artifact: true

  build-and-push-backends:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    needs: [ lint-all-services]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Check if backend1 has changed
        id: check_backend1
        uses: ./.github/actions/has-changed
        with:
          dir: backend1

      - name: Check if backend2 has changed
        id: check_backend2
        uses: ./.github/actions/has-changed
        with:
          dir: backend2
      - name: Set Docker image tag
        if: steps.check_backend1.outputs.changed == 'true' || steps.check_backend2.outputs.changed == 'true'
        id: set
        run: |
          echo ${{steps.check_backend1.outputs.changed}} ${{steps.check_backend2.outputs.changed}}
          if [[ "${GITHUB_REF}" =~ ^refs/tags/ ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "tag=${VERSION}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-6)
            echo "tag=dev-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Build and Push Docker Image (backend1)
        if: steps.check_backend1.outputs.changed == 'true'
        uses: ./.github/actions/build-and-push
        with:
          service: backend1
          tag: ${{ steps.set.outputs.tag }}
          package_artifact: true

      - name: Build and Push Docker Image (backend2)
        if: steps.check_backend2.outputs.changed == 'true'
        uses: ./.github/actions/build-and-push
        with:
          service: backend2
          tag: ${{ steps.set.outputs.tag }}
