name: "Lint and Security Checks"
description: "Lint and security checks"
inputs:
  directory:
    description: "Directory to run checks"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.0.0'
        cache: 'yarn'
        cache-dependency-path: '${{ inputs.directory }}/yarn.lock'

    - name: Install Dependencies
      run: cd ${{ inputs.directory }} && yarn install --frozen-lockfile --prefer-offline
      shell: bash

    - name: Run lint & security checks
      shell: bash
      run: |
        ROOT_DIR=$(git rev-parse --show-toplevel)
        echo "Running lint and security checks for ${{ inputs.directory }}..."
        cd "$ROOT_DIR/${{ inputs.directory }}"
        # yarn lint
        # yarn tsc --noEmit
        npm-audit-resolver --production --audit || true
        cd "$ROOT_DIR"
    
