name: "Lint and Security Checks"
description: "Lint and security checks"
inputs:
  directory:
    description: "Directory to run checks"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ${{ inputs.directory }}/node_modules
        key: ${{ runner.os }}-node-${{ inputs.directory }}-${{ hashFiles(format('{0}/yarn.lock', inputs.directory)) }}
        restore-keys: |
          ${{ runner.os }}-node-${{inputs.directory}}

    - name: Run lint & security checks
      shell: bash
      run: |
        ROOT_DIR=$(git rev-parse --show-toplevel)
        echo "Running lint and security checks for ${{ inputs.directory }}..."
        cd "$ROOT_DIR/${{ inputs.directory }}"
        yarn install
        # yarn lint
        # yarn tsc --noEmit
        npm-audit-resolver --production --audit || true
        cd "$ROOT_DIR"
